import { StyleSheet } from "react-native";
export const lightColors = {
  ink: "#20251f",
  muted: "#6c7067",
  gold: "#c7aa54",
  cream: "#f6f5ef",
  line: "#e5e6dd",
  white: "#ffffff",
  surface: "#ffffff",
  soft: "#eaeade",
  accentText: "#70602d",
  body: "#62665c",
  selected: "#eee8d2",
  hero: "#20251f",
  heroText: "#f6f5ef",
  onGold: "#20251f",
};
export const darkColors: typeof lightColors = {
  ...lightColors,
  ink: "#f3f2e9",
  muted: "#b0b5a8",
  cream: "#141713",
  line: "#373d33",
  surface: "#20251f",
  soft: "#2c3329",
  accentText: "#dbc477",
  body: "#c4c9bc",
  selected: "#45402c",
};
export function createStyles(c: typeof lightColors) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: c.cream },
    shell: { flex: 1, width: "100%", maxWidth: 720, alignSelf: "center" },
    flex: { flex: 1, minWidth: 0 },
    pageTitleCompact: { fontSize: 32, lineHeight: 38 },
    largeDateCompact: { padding: 20 },
    detailHeading: { flex: 1, textAlign: "center", paddingHorizontal: 8 },
    noticeContent: { padding: 24, gap: 20 },
    contentCompact: { paddingHorizontal: 16 },
    headerCompact: { paddingHorizontal: 16 },
    heroCompact: { padding: 22, minHeight: 310 },
    heroTitleCompact: { fontSize: 42, lineHeight: 46, letterSpacing: -1.5 },
    giveTitleCompact: { fontSize: 36, lineHeight: 42 },
    smallImageCompact: { width: 64, height: 64 },
    messageRowInfo: { flex: 1, minWidth: 0, padding: 0, paddingRight: 34 },
    scroll: { flex: 1 },
    content: {
      paddingHorizontal: 22,
      paddingTop: 18,
      paddingBottom: 28,
      gap: 14,
    },
    header: {
      paddingHorizontal: 22,
      paddingVertical: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderBottomWidth: 1,
      borderColor: c.line,
    },
    brand: {
      flexDirection: "row",
      gap: 10,
      alignItems: "center",
      flex: 1,
      minWidth: 0,
    },
    brandMark: {
      flexShrink: 0,
      width: 42,
      height: 42,
    },
    brandName: {
      fontSize: 13,
      fontWeight: "800",
      letterSpacing: 1.4,
      color: c.ink,
    },
    brandPlace: { fontSize: 8, letterSpacing: 2, color: c.muted, marginTop: 4 },
    iconButton: {
      minWidth: 44,
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
    },
    welcomeRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
      flexWrap: "wrap",
    },
    eyebrow: {
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 1.6,
      color: c.accentText,
      marginTop: 2,
    },
    locationPill: { flexDirection: "row", alignItems: "center", gap: 6 },
    dot: { width: 5, height: 5, borderRadius: 3, backgroundColor: "#708351" },
    pillText: { fontSize: 10, color: c.muted },
    hero: {
      backgroundColor: c.hero,
      borderRadius: 24,
      padding: 28,
      overflow: "hidden",
      gap: 16,
      minHeight: 340,
      justifyContent: "center",
    },
    heroCircle: {
      position: "absolute",
      right: -120,
      top: -45,
      width: 360,
      height: 360,
      borderRadius: 180,
      borderWidth: 55,
      borderColor: "#30372b",
      transform: [{ rotate: "-30deg" }],
    },
    heroEyebrow: {
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 2,
      color: c.gold,
    },
    heroTitle: {
      fontSize: 54,
      lineHeight: 57,
      fontWeight: "800",
      letterSpacing: -2,
      color: c.heroText,
    },
    heroBody: { fontSize: 15, lineHeight: 24, color: "#e0e2d8", maxWidth: 380 },
    heroButton: {
      backgroundColor: c.gold,
      borderRadius: 12,
      paddingHorizontal: 18,
      minHeight: 48,
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 28,
      marginTop: 4,
    },
    serviceStrip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 13,
    },
    serviceTitle: { fontSize: 13, fontWeight: "700", color: c.ink },
    meta: { fontSize: 11, lineHeight: 18, color: c.muted, marginTop: 3 },
    quickActions: {
      flexDirection: "row",
      paddingVertical: 8,
      justifyContent: "space-around",
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: c.line,
    },
    quickAction: { alignItems: "center", padding: 8, gap: 7, flex: 1 },
    quickIcon: {
      height: 43,
      width: 43,
      borderRadius: 14,
      backgroundColor: c.soft,
      justifyContent: "center",
      alignItems: "center",
    },
    quickText: {
      fontSize: 12,
      fontWeight: "600",
      color: c.ink,
      textAlign: "center",
    },
    section: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 14,
      gap: 8,
    },
    sectionTitle: {
      fontSize: 21,
      fontWeight: "700",
      color: c.ink,
      letterSpacing: -0.6,
      flexShrink: 1,
    },
    textAction: { minHeight: 44, justifyContent: "center" },
    actionText: { fontSize: 11, fontWeight: "700", color: c.accentText },
    messageCard: {
      backgroundColor: c.surface,
      borderRadius: 18,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: c.line,
    },
    messageRow: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      gap: 12,
    },
    messageImage: {
      aspectRatio: 16 / 9,
      backgroundColor: c.hero,
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
      borderRadius: 16,
    },
    fillImage: {
      position: "absolute",
      width: "100%",
      height: "100%",
      resizeMode: "cover",
    },
    smallImage: {
      width: 82,
      height: 76,
      flexShrink: 0,
      backgroundColor: c.hero,
      borderRadius: 10,
      overflow: "hidden",
      justifyContent: "center",
      alignItems: "center",
    },
    play: {
      height: 46,
      width: 46,
      borderRadius: 23,
      backgroundColor: "#20251fcc",
      alignItems: "center",
      justifyContent: "center",
    },
    imageLabel: {
      position: "absolute",
      top: 13,
      left: 13,
      backgroundColor: c.cream,
      paddingHorizontal: 9,
      paddingVertical: 6,
      borderRadius: 5,
    },
    imageLabelText: {
      fontSize: 8,
      fontWeight: "800",
      letterSpacing: 1,
      color: c.ink,
    },
    messageInfo: { padding: 16, gap: 9, paddingRight: 42 },
    cardTitle: {
      fontSize: 16,
      fontWeight: "700",
      lineHeight: 22,
      color: c.ink,
    },
    save: {
      position: "absolute",
      right: 5,
      bottom: 12,
      width: 44,
      height: 44,
      justifyContent: "center",
      alignItems: "center",
    },
    eventCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.surface,
      borderRadius: 16,
      padding: 15,
      gap: 15,
      borderWidth: 1,
      borderColor: c.line,
    },
    dateBadge: {
      width: 52,
      paddingVertical: 10,
      backgroundColor: c.soft,
      borderRadius: 10,
      alignItems: "center",
    },
    month: {
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 1,
      color: c.accentText,
    },
    day: { fontSize: 27, fontWeight: "700", color: c.ink },
    connectBanner: {
      backgroundColor: c.soft,
      borderRadius: 20,
      padding: 23,
      marginTop: 17,
      gap: 13,
    },
    body: { fontSize: 14, lineHeight: 23, color: c.body },
    button: {
      backgroundColor: c.gold,
      minHeight: 49,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 13,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 10,
    },
    secondary: {
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.line,
    },
    buttonText: {
      fontSize: 13,
      fontWeight: "700",
      color: c.onGold,
      flexShrink: 1,
    },
    pressed: { opacity: 0.72 },
    announcement: {
      borderRadius: 16,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: c.line,
      backgroundColor: c.surface,
    },
    announcementImage: { width: "100%", aspectRatio: 2, resizeMode: "cover" },
    footer: {
      alignItems: "center",
      marginTop: 28,
      paddingTop: 22,
      borderTopWidth: 1,
      borderColor: c.line,
      gap: 5,
    },
    footerBrand: {
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 2,
      color: c.muted,
    },
    footnote: {
      fontSize: 11,
      color: c.muted,
      lineHeight: 17,
      textAlign: "center",
    },
    navSafe: {
      backgroundColor: c.surface,
      borderTopWidth: 1,
      borderColor: c.line,
    },
    nav: {
      flexDirection: "row",
      paddingHorizontal: 8,
      paddingTop: 8,
      paddingBottom: 5,
    },
    navItem: {
      flex: 1,
      minWidth: 0,
      alignItems: "center",
      gap: 4,
      minHeight: 56,
      paddingBottom: 4,
    },
    navIcon: { paddingVertical: 4, paddingHorizontal: 14, borderRadius: 14 },
    navIconActive: { backgroundColor: c.selected },
    navText: { fontSize: 11, color: c.muted, textAlign: "center" },
    navTextActive: { fontWeight: "800", color: c.ink },
    pageTitle: {
      fontSize: 37,
      fontWeight: "800",
      letterSpacing: -1.4,
      color: c.ink,
      lineHeight: 43,
    },
    lead: { fontSize: 16, lineHeight: 24, color: c.muted, marginBottom: 10 },
    search: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: c.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.line,
      paddingLeft: 14,
      minHeight: 50,
    },
    searchInput: {
      flex: 1,
      minHeight: 50,
      fontSize: 15,
      color: c.ink,
      minWidth: 0,
      paddingRight: 10,
    },
    filters: {
      flexDirection: "row",
      gap: 9,
      flexWrap: "wrap",
      marginVertical: 6,
    },
    filter: {
      minHeight: 44,
      justifyContent: "center",
      paddingHorizontal: 18,
      paddingVertical: 13,
      borderRadius: 24,
      backgroundColor: c.soft,
    },
    filterActive: { backgroundColor: c.gold },
    filterText: { fontSize: 12, fontWeight: "600", color: c.ink },
    filterTextActive: { color: c.onGold },
    empty: {
      padding: 28,
      alignItems: "center",
      gap: 13,
      backgroundColor: c.soft,
      borderRadius: 16,
    },
    visitCard: {
      padding: 24,
      gap: 18,
      backgroundColor: c.soft,
      borderRadius: 20,
      marginVertical: 6,
    },
    linkRow: {
      flexDirection: "row",
      alignItems: "center",
      padding: 18,
      backgroundColor: c.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.line,
      gap: 14,
    },
    giveHero: {
      padding: 26,
      paddingVertical: 40,
      backgroundColor: c.hero,
      borderRadius: 24,
      gap: 23,
    },
    giveIcon: {
      width: 78,
      height: 78,
      borderRadius: 39,
      borderWidth: 1,
      borderColor: "#606543",
      alignItems: "center",
      justifyContent: "center",
    },
    giveTitle: {
      fontSize: 44,
      fontWeight: "800",
      letterSpacing: -1.5,
      color: c.heroText,
    },
    detailHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderColor: c.line,
    },
    largeDate: {
      padding: 24,
      gap: 15,
      backgroundColor: c.soft,
      borderRadius: 20,
    },
    noticeBackdrop: {
      flex: 1,
      backgroundColor: "#00000066",
      justifyContent: "center",
      alignItems: "center",
      padding: 25,
    },
    notice: {
      width: "100%",
      maxWidth: 420,
      maxHeight: "85%",
      backgroundColor: c.cream,
      borderRadius: 20,
      overflow: "hidden",
    },
    busy: {
      position: "absolute",
      top: 80,
      right: 20,
      padding: 12,
      backgroundColor: c.gold,
      borderRadius: 30,
    },
  });
}
